import { Center, VStack } from "@chakra-ui/react";
import Head from "next/head";

function Blog() {
  return (
    <>
      <Head>
        <title>Blog – Pravasta Caraka</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack spacing={16} maxW="2xl" mx="auto" justify="center" alignItems="start">
        <Center as="section" w="full">
          Coming soon...
        </Center>
      </VStack>
    </>
  );
}

export default Blog;
